# Generated by Django 2.2.4 on 2019-08-30 08:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190830_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['id'], 'verbose_name': 'Описание', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Категория', max_length=50, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='description',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Категория', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.TextField(help_text='Описание', verbose_name='Описание'),
        ),
    ]
